### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by irinatta** [dd-hendon/HLT1#1]
nice start! however the hlt seems to be incomplete. keep practicing and add the rest of the files once you are ready. :)

**Comment by dd-hendon** [comment]
Thanks! Apologies I didn't realise I had to create more than the one page, could I please ask what other html files I should create? Thanks!

**Comment by dd-hendon** [comment]
Ok I think I now have the required amount of pages, the starting page (index.html) and three pages linked from that. 

1. Home, which displays a simple message and info
2. Profile, which has some personal information  
3. Programming, with some starter links for learning
